/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author victor_preis
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        produtos2 = new javax.swing.JMenu();
        clientes = new javax.swing.JMenu();
        fornecedor = new javax.swing.JMenu();
        funcionarios = new javax.swing.JMenu();
        servicos = new javax.swing.JMenu();
        produtos = new javax.swing.JMenu();
        clientes1 = new javax.swing.JMenu();
        produtos3 = new javax.swing.JMenu();
        produtos4 = new javax.swing.JMenu();
        produtos1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/StockIcon.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText(" System For Inventory Control");

        produtos2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/book of record.png"))); // NOI18N
        produtos2.setText("Cadastro");
        produtos2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                produtos2MousePressed(evt);
            }
        });

        clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Clients.png"))); // NOI18N
        clientes.setText("Clientes");
        clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                clientesMousePressed(evt);
            }
        });
        produtos2.add(clientes);

        fornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Truck_Yellow.png"))); // NOI18N
        fornecedor.setText("Fornecedores");
        fornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fornecedorMousePressed(evt);
            }
        });
        produtos2.add(fornecedor);

        funcionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Workers.png"))); // NOI18N
        funcionarios.setText("Funcionarios");
        funcionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                funcionariosMousePressed(evt);
            }
        });
        produtos2.add(funcionarios);

        servicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/service.png"))); // NOI18N
        servicos.setText("Serviços");
        servicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                servicosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                servicosMousePressed(evt);
            }
        });
        produtos2.add(servicos);

        produtos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Product-documentation.png"))); // NOI18N
        produtos.setText("Produtos");
        produtos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                produtosMousePressed(evt);
            }
        });
        produtos2.add(produtos);

        clientes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/8.png"))); // NOI18N
        clientes1.setText("Estoque");
        clientes1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientes1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                clientes1MousePressed(evt);
            }
        });
        produtos2.add(clientes1);

        jMenuBar1.add(produtos2);

        produtos3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/childish_Help.png"))); // NOI18N
        produtos3.setText("Ajuda");
        produtos3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                produtos3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                produtos3MousePressed(evt);
            }
        });
        jMenuBar1.add(produtos3);

        produtos4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/emotion_what.png"))); // NOI18N
        produtos4.setText("Sobre");
        produtos4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                produtos4MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                produtos4MousePressed(evt);
            }
        });
        jMenuBar1.add(produtos4);

        produtos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Exit.png"))); // NOI18N
        produtos1.setText("Sair");
        produtos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                produtos1MousePressed(evt);
            }
        });
        jMenuBar1.add(produtos1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(376, 376, 376)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientesMousePressed
        new clientes().setVisible(true);
    }//GEN-LAST:event_clientesMousePressed

    private void produtos1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produtos1MousePressed
        dispose();
    }//GEN-LAST:event_produtos1MousePressed

    private void fornecedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fornecedorMousePressed
       new fornecedores().setVisible(true);
    }//GEN-LAST:event_fornecedorMousePressed

    private void funcionariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_funcionariosMousePressed
        new funcionarios().setVisible(true);
    }//GEN-LAST:event_funcionariosMousePressed

    private void servicosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_servicosMousePressed
      new servico().setVisible(true);
    }//GEN-LAST:event_servicosMousePressed

    private void produtosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produtosMousePressed
      new produto().setVisible(true);
    }//GEN-LAST:event_produtosMousePressed

    private void produtos2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produtos2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_produtos2MousePressed

    private void produtos3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produtos3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_produtos3MousePressed

    private void clientes1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientes1MousePressed
       new estoque().setVisible(true);
    }//GEN-LAST:event_clientes1MousePressed

    private void clientes1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientes1MouseClicked
       new estoque().setVisible(true);
    }//GEN-LAST:event_clientes1MouseClicked

    private void produtos4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produtos4MousePressed
      
    }//GEN-LAST:event_produtos4MousePressed

    private void produtos4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produtos4MouseClicked
        new sobre().setVisible(true);
    }//GEN-LAST:event_produtos4MouseClicked

    private void servicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_servicosMouseClicked
      new servico().setVisible(true);
    }//GEN-LAST:event_servicosMouseClicked

    private void produtos3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produtos3MouseClicked
      new ajuda().setVisible(true);
    }//GEN-LAST:event_produtos3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu clientes;
    private javax.swing.JMenu clientes1;
    private javax.swing.JMenu fornecedor;
    private javax.swing.JMenu funcionarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu produtos;
    private javax.swing.JMenu produtos1;
    private javax.swing.JMenu produtos2;
    private javax.swing.JMenu produtos3;
    private javax.swing.JMenu produtos4;
    private javax.swing.JMenu servicos;
    // End of variables declaration//GEN-END:variables
}
